#!/bin/sh

case "$1" in
 start)
	echo "starting aesdsocket application in daemon mode with the -d option"
	start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket --d
 	;;
 stop)
	echo "stoping aesdsocket application"
	start-stop-daemon -K -n aesdsocket
	;;
 *)
	echo "Usage : $0 start|stop"
	exit 1
 esac
 exit 0
